export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  PRINCIPAL: 'PRINCIPAL',
  TEACHER: 'TEACHER',
  STUDENT: 'STUDENT',
  PARENT: 'PARENT'
}

export const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  HALF_DAY: 'HALF_DAY',
  LEAVE: 'LEAVE'
}

export const EXAM_TYPES = {
  UNIT_TEST: 'UNIT_TEST',
  MIDTERM: 'MIDTERM',
  FINAL: 'FINAL',
  ANNUAL: 'ANNUAL',
  PRACTICAL: 'PRACTICAL',
  OTHER: 'OTHER'
}